import NavBar from '@/components/nav_bar'
import './globals.css'
import { Space_Grotesk } from 'next/font/google'
import Footer from '@/components/footer'

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <div className='bg-[#161C30] text-sm md:text-base'>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  )
}
